[window] 
opacity = 0.7
[scrolling]
history = 15000
multiplier = 5

[font]
normal = {family ="Cascadia Code", style="Regular"}

[colors]
  [colors.primary]
    foreground = '#f7eded'

[cursor]
style = { shape= "Beam" , blinking= "Always"}
blink_interval = 900

