[window] 
opacity = 0.5
[window.padding]
x=5 
y=5
[scrolling]
history = 1000
multiplier = 3

[font]
normal = {family ="Cascadia Code", style="mono"}

[colors]
  [colors.primary]
    foreground = "#e8e6f5"
   
  [colors.search]

[cursor]
style = { shape= "Beam" , blinking= "Always"}
blink_interval = 500

